apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/deployment.yaml
- ../../base/service.yaml
namespace: river-east-dev
images:
- name: aheadaviation/river-east-webapi
  newTag: 1.0.0
namePrefix: dev-